// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNKvzl9RMyoonD_popSf-tJli1vwzblE4',
    appId: '1:832930058023:web:32bf44f7ca885edd8b6302',
    messagingSenderId: '832930058023',
    projectId: 'phone-auth-c337f',
    authDomain: 'phone-auth-c337f.firebaseapp.com',
    storageBucket: 'phone-auth-c337f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-f6XraHPGytBBJNVUBVFALWx-HmuxVXM',
    appId: '1:832930058023:android:835be73b7baea5658b6302',
    messagingSenderId: '832930058023',
    projectId: 'phone-auth-c337f',
    storageBucket: 'phone-auth-c337f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTcpLsbXx7ld1kDZLiRJ0dHjMFD2Ad8vM',
    appId: '1:832930058023:ios:df839cd5094b12628b6302',
    messagingSenderId: '832930058023',
    projectId: 'phone-auth-c337f',
    storageBucket: 'phone-auth-c337f.appspot.com',
    androidClientId: '832930058023-jq2ovtrt2m8q9fscqh3j0k8adrsl0t2q.apps.googleusercontent.com',
    iosClientId: '832930058023-pgvtk0ifm950oroo5c3m6pp1uoot2e7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuth',
  );
}
